name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.6
  dotenv: ^4.2.0
  http: ^1.5.0
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  postgres: ^2.6.0
  logging: ^1.3.0

  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  lints: ^5.0.0
  test: ^1.26.3


